name: pytorch-latest

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.8
  - Pillow=9.1.0 
  - tqdm
  - jsonpickle
  - humanfriendly
  - numpy
  - matplotlib
  - opencv
  - requests

  - pandas
  - seaborn>=0.11.0
  - PyYAML>=5.3.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8